version: '3'

services:
  ros-master:
    image: docker.io/an2ancan/ros_dev:latest
    command: stdbuf -o L roscore
    network_mode: host
    command: bash -c "roscore"
    
  gazebo:
    image: docker.io/an2ancan/ros_dev:latest
    depends_on:
      - ros-master
    network_mode: host
    environment:
      - "XAUTHORITYS"
      - "DISPLAY"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
    - "/dev/dri/"
    command: bash -c " . devel/setup.bash && roslaunch --wait simple_scene gazebo.launch"

  planning:
    image: docker.io/an2ancan/ros_dev:latest
    depends_on:
      - gazebo
    network_mode: host
    command: bash -c "sleep 10; . devel/setup.bash && roslaunch simple_scene planning.launch"
